- name: 'Sean Heath configuration of Pop_OS'
  hosts: 127.0.0.1
  connection: local
  vars:
    packages:
      - atom
      - progress
      - exfat-utils
      - vim
      - keepassxc
      - google-chrome-stable
      - aptitude
      - network-manager-openvpn
      - evince
      - virtualenv
      - tree
      - golang
      - python3-pip
      - python3-dev
      - python3-pexpect
      - python-pexpect
      - build-essential
      - cmake
      - gnome-tweak-tool
      - libaio1
      - htop
      - secure-delete
      - gnome-shell-extension-appindicator
      - plank
      - virt-manager
      - libnextcloudsync0=2.3.3-20171224.060956~zesty1
      - nextcloud-client
      - qownnotes
      - dconf-editor
      - python-psutil
    nordvpn_version: "1.0.0"
        
  tasks:
    - name: Clean up home directory
      file:
        path: "{{ item }}"
        state: absent
      with_items:
          - ~/Documents/
          - ~/Music/
          - ~/Pictures/
          - ~/Templates/
          - ~/Videos/

    - name: create flag directory
      file:
        path: 'flag'
        state: directory

    - name: Install dirmngr
      become: yes
      apt:
        name: dirmngr
        state: present

    - name: Add Nextcloud apt key
      become: yes
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: AD3DD469
        state: present

    - name: Add Google Chrome apt key
      become: yes
      apt_key:
        url: 'https://dl-ssl.google.com/linux/linux_signing_key.pub'
        state: present

    - name: Add Google Chrome repo
      become: yes
      copy:
        content: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
        dest: "/etc/apt/sources.list.d/google-chrome.list"

    - name: Add NextCloud repo
      become: yes
      copy:
        src: files/nextcloud.list
        dest: /etc/apt/sources.list.d/nextcloud.list

    - name: Add QOwnNotes repo
      become: yes
      apt_repository:
        repo: ppa:pbek/qownnotes
        state: present

    - name: Add nordvpn repo
      apt:
        deb: 'https://repo.nordvpn.com/deb/nordvpn/debian/pool/main/nordvpn-release_{{nordvpn_version}}_all.deb'

    - name: Install packages
      become: yes
      apt:
        name: "{{ packages }}"
        update_cache: yes
        state: present
        autoclean: yes
        autoremove: yes
      vars:

    - name: hold libnextcloudsync0
      become: yes
      dpkg_selections:
              name: libnextcloudsync0
              selection: hold

    - name: Add user to libvirt group
      become: yes
      user:
        name: "{{ ansible_user_id }}"
        append: yes
        group: libvirt

    - name: Clone vim repository
      git:
        repo: 'https://github.com/seandheath/vim.git'
        dest: '~/.vim'
        force: yes
        version: master
        update: yes

    - name: Run vim setup script
      command: "{{ item }}"
      with_items:
        - /bin/bash ~/.vim/setup.sh
      
    - name: Clone bash repository
      git:
        repo: 'https://seandheath@github.com/seandheath/bash.git'
        dest: '~/.bash'
        version: master
        force: yes
        update: yes

    - name: Run bash setup script
      command: "{{ item }}"
      with_items:
        - '/bin/bash ~/.bash/setup.sh'

    - name: Install PEDA for gdb
      become: yes
      git:
        repo: 'https://github.com/longld/peda.git'
        dest: '/opt/peda'
        version: master
        update: yes
      register: peda_status

    - name: Set PEDA up with .gdbinit
      lineinfile:
        state: present
        path: '~/.gdbinit'
        line: "source /opt/peda/peda.py"
        create: yes
      when: peda_status.changed

    - name: Check if Keybase is installed
      command: 'dpkg-query -W keybase'
      register: keybase_status
      failed_when: keybase_status.rc > 1
      changed_when: keybase_status.rc == 1

    - name: Download Keybase
      get_url:
        url: 'https://prerelease.keybase.io/keybase_amd64.deb'
        dest: '/tmp/keybase.deb'
      when: keybase_status.rc == 1

    - name: Install Keybase
      become: yes
      apt:
        deb: '/tmp/keybase.deb'
      when: keybase_status.rc == 1

    - name: Install nordnm
      become: yes
      pip:
        name: nordnm
        executable: pip3

    - name: Install gTile extension
      git:
        repo: 'https://github.com/gTile/gTile'
        dest: '~/.local/share/gnome-shell/extensions/gTile@vibou'
        update: yes

    - name: Fix touchpad on suspend
      become: yes
      copy:
        src: 'files/touchpad'
        dest: '/lib/systemd/system-sleep/touchpad'
        mode: 0755

    - name: Check if rust is installed
      command: 'which rustc'
      register: rust_status
      ignore_errors: True

    - name: Install rustup
      become: yes
      get_url:
        url: 'https://sh.rustup.rs'
        dest: '/usr/local/bin/rustup'
        mode: 0755
      when: rust_status.rc == 1

    - name: Install rust
      expect:
        command: 'rustup'
        responses:
          '>': '1'
      when: rust_status.rc == 1

    - name: Check if YouCompleteMe has been installed
      stat:
        path: 'flag/vim-ycm-complete'
      register: ycm_status

    - name: Update YouCompleteMe
      shell: 'git submodule update --init --recursive'
      args:
        chdir: '~/.vim/plugged/YouCompleteMe'
      when: ycm_status.stat.exists == false

    - name: Install YouCompleteMe
      shell: '. ~/.cargo/env && python3 ~/.vim/plugged/YouCompleteMe/install.py --clang-completer --rust-completer'
      when: ycm_status.stat.exists == false

    - name: Set vim-ycm-complete 
      file:
        path: 'flag/vim-ycm-complete'
        state: touch
      when: ycm_status.stat.exists == false

    - name: Create folders for ssh-agent config
      file:
        path: '~/.config/autostart'
        state: directory

    - name: Move gnome-keyring file to disable ssh-agent
      copy:
        src: "/etc/xdg/autostart/gnome-keyring-ssh.desktop"
        dest: "~/.config/autostart/gnome-keyring-ssh.desktop"

    - name: Disable gnome-keyring ssh-agent
      lineinfile:
        state: present
        path: "~/.config/autostart/gnome-keyring-ssh.desktop"
        line: "Hidden=true"

    - name: Disable gnome-keyring ssh-agent
      lineinfile:
        state: present
        path: "~/.config/autostart/gnome-keyring-ssh.desktop"
        line: "X-GNOME-Autostart-enabled=false"

    - name: Ensure user systemd folder exists
      file:
        path: '~/.config/systemd/user/'
        state: directory
        recurse: yes

    - name: Add ssh-agent to systemd
      copy:
        src: 'files/ssh-agent.service'
        dest: '~/.config/systemd/user/ssh-agent.service'
        mode: 0755

    - name: Enable ssh-agent service
      systemd:
        enabled: yes
        state: started
        user: yes
        name: ssh-agent

    - name: get UID
      shell: 'id -u'
      register: uid

    - name: Fix XDG_RUNTIME_DIR
      lineinfile:
        state: present
        path: "~/.pam_environment"
        line: 'SSH_AUTH_SOCK DEFAULT="/run/user/{{uid}}/ssh-agent.socket"'

    - name: Fix Gnome keyring overwriting SSH_AUTH_SOCK
      lineinfile:
        state: present
        path: "~/.pam_environment"
        line: 'GSM_SKIP_SSH_AGENT_WORKAROUND=1'

    - name: Fix alt-tab
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/switch-windows"
        value: "['<Alt>Tab']"
        state: present

    - name: Fix super-tab
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/switch-applications"
        value: "['<Super>Tab']"
        state: present

    - name: Fix home keybinding
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/home"
        value: "'<Super>e'"
        state: present

    - name: Fix terminal keybinding binding
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding"
        value: "'<Primary><Alt>t'"
        state: present

    - name: Fix terminal keybinding command
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command"
        value: "'gnome-terminal'"
        state: present

    - name: Fix terminal keybinding name
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name"
        value: "'terminal'"
        state: present

    - name: Fix screenshot keybinding binding
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/binding"
        value: "'<Primary><Super>s'"
        state: present

    - name: Fix screenshot keybinding command
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/command"
        value: "'gnome-screenshot -ac'"
        state: present

    - name: Fix screenshot keybinding name
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/name"
        value: "'screenshot'"
        state: present

