- name: 'Sean Heath configuration of Pop_OS'
  hosts: 127.0.0.1
  connection: local
  vars:
    packages:
      - atom
      - syncthing
      - vim
      - keepassxc
      - google-chrome-stable
      - aptitude
      - network-manager-openvpn
      - evince
      - virtualenv
      - tree
      - golang
      - python3-pip
      - python3-dev
      - python3-pexpect
      - python-pexpect
      - build-essential
      - cmake
      - gnome-tweak-tool
      - libaio1
      - htop
      - secure-delete
      - syncthing-gtk
      - gnome-shell-extension-appindicator
      - virt-manager
        
  tasks:
    - name: Clean up home directory
      file:
        path: "{{ item }}"
        state: absent
      with_items:
          - ~/Documents/
          - ~/Music/
          - ~/Pictures/
          - ~/Public/
          - ~/Templates/
          - ~/Videos/

    - name: Create extensions directory
      file:
        path: "~/.local/share/gnome-shell/extensions/"
        state: directory
      ignore_errors: True

    - name: Add Google Chrome apt key
      become: yes
      apt_key:
        url: 'https://dl-ssl.google.com/linux/linux_signing_key.pub'
        state: present

    - name: Add Google Chrome repo
      become: yes
      copy:
        content: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
        dest: "/etc/apt/sources.list.d/google-chrome.list"

    - name: Install packages
      become: yes
      apt:
        name: "{{ packages }}"
        update_cache: yes
        state: present
        autoclean: yes
        autoremove: yes
      vars:

    - name: Add user to libvirt group
      become: yes
      user:
        name: "{{ ansible_user_id }}"
        append: yes
        group: libvirt

    - name: Clone vim repository
      git:
        repo: 'https://github.com/seandheath/vim.git'
        dest: '~/.vim'
        version: master
        update: yes
      register: vim_results
      changed_when: "vim_results.after|default('after') != vim_results.before|default('before')"

    - name: Run vim setup script
      command: "{{ item }}"
      with_items:
        - /bin/bash ~/.vim/setup.sh
      when: vim_results.changed
      
    - name: Clone bash repository
      git:
        repo: 'https://seandheath@github.com/seandheath/bash.git'
        dest: '~/.bash'
        version: master
        update: yes
      register: bash_results
      changed_when: "bash_results.after|default('after') != bash_results.before|default('before')"

    - name: Run bash setup script
      command: "{{ item }}"
      with_items:
        - '/bin/bash ~/.bash/setup.sh'
      when: bash_results.changed

    - name: Install PEDA for gdb
      become: yes
      git:
        repo: 'https://github.com/longld/peda.git'
        dest: '/opt/peda'
        version: master
        update: yes
      register: peda_status

    - name: Set PEDA up with .gdbinit
      lineinfile:
        state: present
        path: '~/.gdbinit'
        line: "source /opt/peda/peda.py"
        create: yes
      when: peda_status.changed

    - name: Check if Keybase is installed
      command: 'dpkg-query -W keybase'
      register: keybase_status
      failed_when: keybase_status.rc > 1
      changed_when: keybase_status.rc == 1

    - name: Download Keybase
      get_url:
        url: 'https://prerelease.keybase.io/keybase_amd64.deb'
        dest: '/tmp/keybase.deb'
      when: keybase_status.rc == 1

    - name: Install Keybase
      become: yes
      apt:
        deb: '/tmp/keybase.deb'
      when: keybase_status.rc == 1

    - name: Install nordnm
      become: yes
      pip:
        name: nordnm
        executable: pip3

    - name: Install gTile extension
      git:
        repo: 'https://github.com/gTile/gTile'
        dest: '~/.local/share/gnome-shell/extensions/gTile@vibou'
        update: yes

    - name: Download Dash to Dock
      git:
        repo: 'https://github.com/micheleg/dash-to-dock.git'
        dest: '~/.local/share/gnome-shell/extensions/dash-to-dock@micheleg'
        version: gnome-3.30

    - name: Make Dash-to-Dock
      make:
        chdir: '~/.local/share/gnome-shell/extensions/dash-to-dock@micheleg'

    - name: Install Dash-to-Dock
      make:
        chdir: '~/.local/share/gnome-shell/extensions/dash-to-dock@micheleg'
        target: install

    - name: Fix touchpad on suspend
      become: yes
      copy:
        src: 'files/touchpad'
        dest: '/lib/systemd/system-sleep/touchpad'
        mode: 0755

    - name: Check if rust is installed
      command: 'which rustc'
      register: rust_status
      ignore_errors: True

    - name: Install rustup
      become: yes
      get_url:
        url: 'https://sh.rustup.rs'
        dest: '/usr/local/rustup'
        mode: 0755
      when: rust_status.rc == 1

    - name: Install rust
      expect:
        command: 'rustup'
        responses:
          '>': '1'
      when: rust_status.rc == 1

    - name: Install YouCompleteMe
      shell: '. ~/.cargo/env && python3 ~/.vim/plugged/YouCompleteMe/install.py --clang-completer --rust-completer'

    - name: Move gnome-keyring file to disable ssh-agent
      copy:
        src: "/etc/xdg/autostart/gnome-keyring-ssh.desktop"
        dest: "~/.config/autostart/gnome-keyring-ssh.desktop"

    - name: Disable gnome-keyring ssh-agent
      lineinfile:
        state: present
        path: "~/.config/autostart/gnome-keyring-ssh.desktop"
        line: "Hidden=true"
